### PR TITLE
pipes, subshells and math improvements

### PR DESCRIPTION
**Pull request by ghost**
optimized pipes to avoid stuff like cat|grep|awk|sed and changed math to expr/awk to cut down on more pipes/subshells

### CODE REVIEW

**Comment by ghost** [comment]
Are you seeing any issues with this? Just wondering about the status of the pr

**Comment by gsxryan** [comment]
No, just need to find time to test it

**Comment by JeromeGillard** [comment]
`awk` for the win :-)

**Review by gsxryan — APPROVED** [review]
Nice work! Apologies for the delay in testing.  In my test successrate.sh improved telegraf conf time by:
Previous version:
real    0m3.226s
user    0m0.815s
sys     0m0.599s
New version:
real    0m3.207s
user    0m0.724s
sys     0m0.439s

Tokens.sh script
Old:
real    0m1.173s
user    0m0.124s
sys     0m0.050s
New:
real    0m0.952s
user    0m0.094s
sys     0m0.043s

telegraf conf test improvement on tokens.sh
Old:
real    0m3.165s
user    0m0.764s
sys     0m0.376s
New:
real    0m3.158s
user    0m0.645s
sys     0m0.511s

**Pull request merged**
