### PR TITLE
Multi host dashboard support.

### PR DESCRIPTION
**Pull request by JeromeGillard**
TODO: try to handle interface names (docker0 name vary on my host).

### CODE REVIEW

**Comment by JeromeGillard** [comment]
@gsxryan I guess you have multiple node. Could you give an eye to this version of the dashboard?

**Comment by gsxryan** [comment]
I'm only running a single node, but I do have multiple network interfaces. I'll try it soon

**Comment by JeromeGillard** [comment]
> 
> 
> I'm only running a single node, but I do have multiple network interfaces. I'll try it soon

The problem was for interfaces not all named the same across all my hosts. I was tracking `eth0` on the first and `enp0s25` on the other one. I've now comitted changes in dashboard and README to track `docker0`. But upload & download are inverted witch is logical but not natural to understand.

Anyway, this PR should be OK with one or more hosts, having one or more interfaces.

**Comment by gsxryan** [comment]
I noticed that the throughput chart was inverted on my last test as well.  I have fixed it in my next commit, will push that up soon.

**Review by gsxryan — APPROVED** [review]
It looks like Alerts got nuked, but i'll push those back up next commit as well.

**Pull request merged**
